---
version: "2.2"

services:
  sim_node:
    scale: 20
    image: primordial_particles
    environment:
      - SIM_RADIUS=20
      - SIM_DENSITY=0.032
      - SIM_INTERVAL=80
      - CONNECTION_DEGREE=4
    build:
      dockerfile: docker/Dockerfile
      context: ..
