---
version: "2.2"

services:
  sim_node:
    scale: 10
    image: primordial_particles
    environment:
      - SIM_RADIUS=20
      - SIM_DENSITY=0.04
      - SIM_INTERVAL=80
      - CONNECTION_DEGREE=6
    build:
      dockerfile: docker/Dockerfile
      context: ..
