---
version: "2.2"

services:
  sim_node:
    scale: 32
    image: wzli/primordial_particles
    environment:
      - SIM_RADIUS=20
      - SIM_DENSITY=0.04
      - SIM_INTERVAL=50
    build:
      dockerfile: docker/Dockerfile
      context: ..
